/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author akshxy
 */
public class calci extends javax.swing.JFrame {

    double firstNumber;
    double secondNumber;
    double result;
    String operation;

    public calci() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jtxtDisplay = new javax.swing.JTextField();
        JBTn1 = new javax.swing.JButton();
        JBTn2 = new javax.swing.JButton();
        JBTn3 = new javax.swing.JButton();
        JBTn4 = new javax.swing.JButton();
        JBTn5 = new javax.swing.JButton();
        JBTn6 = new javax.swing.JButton();
        JBTn7 = new javax.swing.JButton();
        JBTn8 = new javax.swing.JButton();
        JBTn9 = new javax.swing.JButton();
        JBTn0 = new javax.swing.JButton();
        JBTnPlus = new javax.swing.JButton();
        JBTnMinus = new javax.swing.JButton();
        JBTnDivide = new javax.swing.JButton();
        JBTnPlusMinus = new javax.swing.JButton();
        JBTnMultiply = new javax.swing.JButton();
        JBTnC = new javax.swing.JButton();
        JBTnPoint = new javax.swing.JButton();
        JBTnEqual = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        jLabel1.setText("Simple Calculator");

        jtxtDisplay.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtDisplayActionPerformed(evt);
            }
        });

        JBTn1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        JBTn1.setText("1");
        JBTn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTn1ActionPerformed(evt);
            }
        });

        JBTn2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        JBTn2.setText("2");
        JBTn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTn2ActionPerformed(evt);
            }
        });

        JBTn3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        JBTn3.setText("3");
        JBTn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTn3ActionPerformed(evt);
            }
        });

        JBTn4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        JBTn4.setText("4");
        JBTn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTn4ActionPerformed(evt);
            }
        });

        JBTn5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        JBTn5.setText("5");
        JBTn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTn5ActionPerformed(evt);
            }
        });

        JBTn6.setFont(new java.awt.Font("Times New Roman", 1, 21)); // NOI18N
        JBTn6.setText("6");
        JBTn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTn6ActionPerformed(evt);
            }
        });

        JBTn7.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        JBTn7.setText("7");
        JBTn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTn7ActionPerformed(evt);
            }
        });

        JBTn8.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        JBTn8.setText("8");
        JBTn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTn8ActionPerformed(evt);
            }
        });

        JBTn9.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        JBTn9.setText("9");
        JBTn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTn9ActionPerformed(evt);
            }
        });

        JBTn0.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        JBTn0.setText("0");
        JBTn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTn0ActionPerformed(evt);
            }
        });

        JBTnPlus.setFont(new java.awt.Font("Times New Roman", 1, 25)); // NOI18N
        JBTnPlus.setText("+");
        JBTnPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTnPlusActionPerformed(evt);
            }
        });

        JBTnMinus.setFont(new java.awt.Font("Times New Roman", 1, 25)); // NOI18N
        JBTnMinus.setText("-");
        JBTnMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTnMinusActionPerformed(evt);
            }
        });

        JBTnDivide.setFont(new java.awt.Font("Times New Roman", 1, 25)); // NOI18N
        JBTnDivide.setText("/");
        JBTnDivide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTnDivideActionPerformed(evt);
            }
        });

        JBTnPlusMinus.setFont(new java.awt.Font("Times New Roman", 1, 25)); // NOI18N
        JBTnPlusMinus.setText("+/-");
        JBTnPlusMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTnPlusMinusActionPerformed(evt);
            }
        });

        JBTnMultiply.setFont(new java.awt.Font("Times New Roman", 1, 25)); // NOI18N
        JBTnMultiply.setText("*");
        JBTnMultiply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTnMultiplyActionPerformed(evt);
            }
        });

        JBTnC.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        JBTnC.setText("C");
        JBTnC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTnCActionPerformed(evt);
            }
        });

        JBTnPoint.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        JBTnPoint.setText(".");
        JBTnPoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTnPointActionPerformed(evt);
            }
        });

        JBTnEqual.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        JBTnEqual.setText("=");
        JBTnEqual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBTnEqualActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(JBTn1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(JBTn2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(JBTn3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JBTnPlus, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtDisplay, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(JBTn4, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(JBTn5, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(JBTn6, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(JBTnMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(JBTn7, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(JBTn8, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(JBTn9, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(JBTnDivide, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(JBTn0, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(JBTnPlusMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                        .addComponent(JBTnMultiply, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(JBTnC, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(JBTnPoint, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(JBTnEqual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtxtDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBTn1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBTn2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBTn3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBTnPlus, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBTn4, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBTn5, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBTn6, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBTnMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBTn9, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBTn8, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBTn7, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBTnDivide, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBTn0, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBTnPlusMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBTnMultiply, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBTnC, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBTnPoint, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBTnEqual, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtDisplayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtDisplayActionPerformed

    private void JBTn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTn1ActionPerformed
        String EnterNumber = jtxtDisplay.getText() + JBTn1.getText();
        jtxtDisplay.setText(EnterNumber);
    }//GEN-LAST:event_JBTn1ActionPerformed

    private void JBTn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTn2ActionPerformed
        String EnterNumber = jtxtDisplay.getText() + JBTn2.getText();
        jtxtDisplay.setText(EnterNumber);
    }//GEN-LAST:event_JBTn2ActionPerformed

    private void JBTnPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTnPlusActionPerformed
        firstNumber = Double.parseDouble(jtxtDisplay.getText());
        jtxtDisplay.setText("");
        operation = "+";
    }//GEN-LAST:event_JBTnPlusActionPerformed

    private void JBTn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTn4ActionPerformed
        String EnterNumber = jtxtDisplay.getText() + JBTn4.getText();
        jtxtDisplay.setText(EnterNumber);
    }//GEN-LAST:event_JBTn4ActionPerformed

    private void JBTn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTn8ActionPerformed
        String EnterNumber = jtxtDisplay.getText() + JBTn8.getText();
        jtxtDisplay.setText(EnterNumber);
    }//GEN-LAST:event_JBTn8ActionPerformed

    private void JBTn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTn5ActionPerformed
        String EnterNumber = jtxtDisplay.getText() + JBTn5.getText();
        jtxtDisplay.setText(EnterNumber);
    }//GEN-LAST:event_JBTn5ActionPerformed

    private void JBTn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTn7ActionPerformed
        // TODO add your handling code here;
        String EnterNumber = jtxtDisplay.getText() + JBTn7.getText();
        jtxtDisplay.setText(EnterNumber);
    }//GEN-LAST:event_JBTn7ActionPerformed

    private void JBTn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTn6ActionPerformed
        // TODO add your handling code here:
        String EnterNumber = jtxtDisplay.getText() + JBTn6.getText();
        jtxtDisplay.setText(EnterNumber);
    }//GEN-LAST:event_JBTn6ActionPerformed

    private void JBTn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTn9ActionPerformed
        // TODO add your handling code here:
        String EnterNumber = jtxtDisplay.getText() + JBTn9.getText();
        jtxtDisplay.setText(EnterNumber);
    }//GEN-LAST:event_JBTn9ActionPerformed

    private void JBTnMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTnMinusActionPerformed
        // TODO add your handling code here:
        firstNumber = Double.parseDouble(jtxtDisplay.getText());
        jtxtDisplay.setText("");
        operation = "-";
    }//GEN-LAST:event_JBTnMinusActionPerformed

    private void JBTnDivideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTnDivideActionPerformed
        // TODO add your handling code here:
        firstNumber = Double.parseDouble(jtxtDisplay.getText());
        jtxtDisplay.setText("");
        operation = "/";
    }//GEN-LAST:event_JBTnDivideActionPerformed

    private void JBTn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTn3ActionPerformed
        // TODO add your handling code here:
        String EnterNumber = jtxtDisplay.getText() + JBTn3.getText();
        jtxtDisplay.setText(EnterNumber);
    }//GEN-LAST:event_JBTn3ActionPerformed

    private void JBTn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTn0ActionPerformed
        // TODO add your handling code here:
        String EnterNumber = jtxtDisplay.getText() + JBTn0.getText();
        jtxtDisplay.setText(EnterNumber);
    }//GEN-LAST:event_JBTn0ActionPerformed

    private void JBTnPlusMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTnPlusMinusActionPerformed
        // TODO add your handling code here:
        double ops = Double.parseDouble(String.valueOf(jtxtDisplay.getText()));
        ops = ops * (-1);
        jtxtDisplay.setText(String.valueOf(ops));
    }//GEN-LAST:event_JBTnPlusMinusActionPerformed

    private void JBTnMultiplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTnMultiplyActionPerformed
        // TODO add your handling code here:
        firstNumber = Double.parseDouble(jtxtDisplay.getText());
        jtxtDisplay.setText("");
        operation = "*";
    }//GEN-LAST:event_JBTnMultiplyActionPerformed

    private void JBTnCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTnCActionPerformed
        // TODO add your handling code here:
        jtxtDisplay.setText("");
    }//GEN-LAST:event_JBTnCActionPerformed

    private void JBTnPointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTnPointActionPerformed
        // TODO add your handling code here:
        firstNumber = Double.parseDouble(jtxtDisplay.getText());
        jtxtDisplay.setText("");
        operation = ".";
    }//GEN-LAST:event_JBTnPointActionPerformed

    private void JBTnEqualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBTnEqualActionPerformed
        String answer;
        secondNumber = Double.parseDouble(jtxtDisplay.getText());
        if (operation == "+") {
            result = firstNumber + secondNumber;
            answer = String.format("%.0f", result);
            jtxtDisplay.setText(answer);
        } else if (operation == "-") {
            result = firstNumber - secondNumber;
            answer = String.format("%.0f", result);
            jtxtDisplay.setText(answer);
        } else if (operation == "*") {
            result = firstNumber * secondNumber;
            answer = String.format("%.0f", result);
            jtxtDisplay.setText(answer);
        } else if (operation == "/") {
            result = firstNumber / secondNumber;
            answer = String.format("%.0f", result);
            jtxtDisplay.setText(answer);
        } 
    }//GEN-LAST:event_JBTnEqualActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(calci.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(calci.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(calci.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(calci.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new calci().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBTn0;
    private javax.swing.JButton JBTn1;
    private javax.swing.JButton JBTn2;
    private javax.swing.JButton JBTn3;
    private javax.swing.JButton JBTn4;
    private javax.swing.JButton JBTn5;
    private javax.swing.JButton JBTn6;
    private javax.swing.JButton JBTn7;
    private javax.swing.JButton JBTn8;
    private javax.swing.JButton JBTn9;
    private javax.swing.JButton JBTnC;
    private javax.swing.JButton JBTnDivide;
    private javax.swing.JButton JBTnEqual;
    private javax.swing.JButton JBTnMinus;
    private javax.swing.JButton JBTnMultiply;
    private javax.swing.JButton JBTnPlus;
    private javax.swing.JButton JBTnPlusMinus;
    private javax.swing.JButton JBTnPoint;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jtxtDisplay;
    // End of variables declaration//GEN-END:variables
}
